swagger: '2.0'
info:
  description: draft elasticsearch
  version: 1.0.0
  title: Elasticsearch rest api
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:9200'
basePath: /
schemes:
  - http
paths:
  /:
    get:
      tags:
        - info
      summary: Get cluster info
      description: 'http://www.elastic.co/guide/'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/MainResponse'
      consumes:
        - ''
  /_cluster/health:
    get:
      tags:
        - cluster
      parameters:
        - name: format
          in: query
          description: 'a short version of the Accept header, e.g. json, yaml'
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ClusterHealthResponse'
  /_cluster/settings:
    put:
      tags: 
        - cluster
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/ClusterSettingsRequest"
      responses:
        200:
          description: OK
      
    
  
  
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Version:
    type: object
    properties:
      number:
        type: string
      build_flavor:
        type: string
      build_type:
        type: string
      build_hash:
        type: string
      build_date:
        type: string
      build_snapshot:
        type: string
      lucene_version:
        type: string
      minimum_wire_compatibility_version:
        type: string
      minimum_index_compatibility_version:
        type: string
  MainResponse:
    type: object
    properties:
      name:
        type: string
      cluster_name:
        type: string
      cluster_uuid:
        type: string
      version:
        $ref: '#/definitions/Version'
      tagline:
        type: string
  ClusterHealthResponse:
    type: object
    properties:
      epoch:
        type: string
      timestamp:
        type: string
      cluster:
        type: string
      status:
        type: string
      node.total:
        type: string
      node.data:
        type: string
      shards:
        type: string
      pri:
        type: string
      relo:
        type: string
      init:
        type: string
      unassign:
        type: string
      pending_tasks:
        type: string
      max_tasks_wait_time:
        type: string
      active_shards_percent:
        type: string
  CatClusterHealth:
    type: array
    items:
      $ref: '#/definitions/ClusterHealthResponse'
  ClusterSettingsRequest:
    type: object
    properties:
      persistent:
        type: object
        additionalProperties:
          type: string
      transient:
        type: object
        additionalProperties:
          type: string
  
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
