/*
 * Elasticsearch rest api
 * draft elasticsearch
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;



/**
 * Model tests for ClusterHealthResponse
 */
public class ClusterHealthResponseTest {
    
    
    
    private final ClusterHealthResponse model = new ClusterHealthResponse();

    
    /**
     * Model tests for ClusterHealthResponse
     */
    @Test
    public void testClusterHealthResponse() {
        // TODO: test ClusterHealthResponse
    }

    
    /**
     * Test the property 'epoch'
     */
    @Test
    public void epochTest() {
        // TODO: test epoch
    }

    
    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    
    /**
     * Test the property 'cluster'
     */
    @Test
    public void clusterTest() {
        // TODO: test cluster
    }

    
    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    
    /**
     * Test the property 'nodeTotal'
     */
    @Test
    public void nodeTotalTest() {
        // TODO: test nodeTotal
    }

    
    /**
     * Test the property 'nodeData'
     */
    @Test
    public void nodeDataTest() {
        // TODO: test nodeData
    }

    
    /**
     * Test the property 'shards'
     */
    @Test
    public void shardsTest() {
        // TODO: test shards
    }

    
    /**
     * Test the property 'pri'
     */
    @Test
    public void priTest() {
        // TODO: test pri
    }

    
    /**
     * Test the property 'relo'
     */
    @Test
    public void reloTest() {
        // TODO: test relo
    }

    
    /**
     * Test the property 'init'
     */
    @Test
    public void initTest() {
        // TODO: test init
    }

    
    /**
     * Test the property 'unassign'
     */
    @Test
    public void unassignTest() {
        // TODO: test unassign
    }

    
    /**
     * Test the property 'pendingTasks'
     */
    @Test
    public void pendingTasksTest() {
        // TODO: test pendingTasks
    }

    
    /**
     * Test the property 'maxTasksWaitTime'
     */
    @Test
    public void maxTasksWaitTimeTest() {
        // TODO: test maxTasksWaitTime
    }

    
    /**
     * Test the property 'activeShardsPercent'
     */
    @Test
    public void activeShardsPercentTest() {
        // TODO: test activeShardsPercent
    }

    
    
    
}
