/*
 * Elasticsearch rest api
 * draft elasticsearch
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Version;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;



/**
 * Model tests for MainResponse
 */
public class MainResponseTest {
    
    
    
    private final MainResponse model = new MainResponse();

    
    /**
     * Model tests for MainResponse
     */
    @Test
    public void testMainResponse() {
        // TODO: test MainResponse
    }

    
    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    
    /**
     * Test the property 'clusterName'
     */
    @Test
    public void clusterNameTest() {
        // TODO: test clusterName
    }

    
    /**
     * Test the property 'clusterUuid'
     */
    @Test
    public void clusterUuidTest() {
        // TODO: test clusterUuid
    }

    
    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    
    /**
     * Test the property 'tagline'
     */
    @Test
    public void taglineTest() {
        // TODO: test tagline
    }

    
    
    
}
