/*
 * Elasticsearch rest api
 * draft elasticsearch
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;



/**
 * Model tests for Version
 */
public class VersionTest {
    
    
    
    private final Version model = new Version();

    
    /**
     * Model tests for Version
     */
    @Test
    public void testVersion() {
        // TODO: test Version
    }

    
    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    
    /**
     * Test the property 'buildFlavor'
     */
    @Test
    public void buildFlavorTest() {
        // TODO: test buildFlavor
    }

    
    /**
     * Test the property 'buildType'
     */
    @Test
    public void buildTypeTest() {
        // TODO: test buildType
    }

    
    /**
     * Test the property 'buildHash'
     */
    @Test
    public void buildHashTest() {
        // TODO: test buildHash
    }

    
    /**
     * Test the property 'buildDate'
     */
    @Test
    public void buildDateTest() {
        // TODO: test buildDate
    }

    
    /**
     * Test the property 'buildSnapshot'
     */
    @Test
    public void buildSnapshotTest() {
        // TODO: test buildSnapshot
    }

    
    /**
     * Test the property 'luceneVersion'
     */
    @Test
    public void luceneVersionTest() {
        // TODO: test luceneVersion
    }

    
    /**
     * Test the property 'minimumWireCompatibilityVersion'
     */
    @Test
    public void minimumWireCompatibilityVersionTest() {
        // TODO: test minimumWireCompatibilityVersion
    }

    
    /**
     * Test the property 'minimumIndexCompatibilityVersion'
     */
    @Test
    public void minimumIndexCompatibilityVersionTest() {
        // TODO: test minimumIndexCompatibilityVersion
    }

    
    
    
}
